---
minimum_pre_commit_version: 1.17.0
default_stages: [commit, push]
repos:

  - repo: local
    hooks:

      - id: codespell
        name: Check Spelling
        description: Checks for common misspellings in text files.
        entry: codespell --ignore-words=.aspell.en.pws
        language: system
        exclude: ^.*\.svg|^poetry.lock
        types: [file, text]

      - id: trailing-whitespace
        name: Trim Trailing Space
        entry: trailing-whitespace-fixer
        language: system
        types: [file, text]

      - id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
        language: system
        types: [file, text]

      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for files that contain merge conflict strings.
        entry: check-merge-conflict
        language: system
        types: [file, text]

      - id: yamllint
        name: yamllint
        description: Lint YAML files.
        entry: yamllint
        language: system
        types: [yaml]

      - id: isort
        name: isort
        description: A Python utility that sorts imports alphabetically
        entry: isort
        language: system
        types: [python]

      - id: autoflake
        name: autoflake
        description: Removes unused imports and unused variables from Python code
        entry: autoflake --remove-all-unused-imports -i -r
        language: system
        types: [python]

      - id: black
        name: Black
        description: Uncompromising Python code formatter
        entry: black --line-length 62
        language: system
        types: [python]

      - id: flake8
        name: Flake8
        description: Python Style Guide Enforcement
        entry: flake8 --config .flake8
        language: system
        types: [python]
